# Sample Bee Configuration
api-addr: 127.0.0.1:1633
swap-enable: 'false'
mainnet: 'true'
full-node: 'false'
cors-allowed-origins: '*'
use-postage-snapshot: 'false'
skip-postage-snapshot: 'true'
resolver-options: https://cloudflare-eth.com
data-dir: DATA_DIR
password: PASSWORD
storage-incentives-enable: 'false'
